In [1]:
import os
import re
Pfad = input("Bitte absoluten Pfad angeben oder ENTER, wenn im Arbeitsverzeichnis:")
if Pfad != "":
    os.chdir(Pfad)
else:
    os.chdir(os.getcwd())

Bitte absoluten Pfad angeben oder ENTER, wenn im Arbeitsverzeichnis:

In [2]:
#Datei lesen
lines = []
import csv
with open('Rezensionen_Schlüsselroman.csv', newline='', encoding="UTF8") as csvfile:
    datumreader = csv.reader(csvfile, delimiter=';', quotechar='|')
    for row in datumreader:
        #print(', '.join(row))#print(row)
        #print(', '.join(row))
        lines.append(', '.join(row))
lines

['\ufeffDie Zeit, 02.06.2002 (Jan Assheuer).',
 'Süddeutsche Zeitung (München), 05.06. 2002 (Joachim Kaiser).',
 'Der Standard (Album), 06.07.2002, S. 1 (Daniela Strigl).',
 'Die Furche, 18.07.2002, S. 15 (Kurt Wimmer).',
 'Frankfurter Rundschau, 27.06.2002, S. 22 (Jochen Hörisch).',
 'Frankfurter Rundschau, 27.06.2002, S. 19 (Ruth Klüger).',
 'Der Tagesspiegel, 27.06.2002, S. 27 (Peter von Becker).',
 'Die Zeit, 27.06.2002, S. 45 (Jens Jessen).',
 'Frankfurter Allgemeine Zeitung, 27.06.2002, S. 47–48 (Jan Philipp Reemtsma).',
 'Oberösterreichische Nachrichten, 05.07.2002, S. 7 (Christian Pichler).',
 'Die Presse (Spectrum), 29.06.2002, S. V (Christoph Bartmann).',
 'Neues Deutschland, 26.06.2002, S. 9 (Hans-Dieter Schütt).',
 'Die Welt, 27.06.2002, S. 28 (Tilman Krause).',
 'Der Freitag, 14.06.2002, S. 14 (Ingo Arend).',
 'Die Zeit, 06.06.2002, S. 39 (Ulrich Greiner).',
 'die tageszeitung, 17.06.2002, S. 20 (Klaus Bittermann).',
 'Neue Zürcher Zeitung, 01.06.2002, S. 33 (Martin Meyer).',
 'Tiroler Tageszeitung (Magazin), 08.06.2002, S. 6 (Sabine Strobl).',
 'Der Freitag, 07.06.2002, S. 11 (Ulrich Müller-Schöll).',
 'Rheinischer Merkur, 06.06.2002, S. 8 (Ulrich Baron).',
 'Rheinischer Merkur, 06.06.2002, S. 8 (Andreas Öhler).',
 'Vorarlberger Nachrichten, 15.06.2002, S. D11 (o. V.)',
 'Der Standard, 03.06.2002, S. 22 (Richard Reichensperger).',
 'profil, 03.06.2002, S. 132 (Willi Winkler).',
 'Der Spiegel, 03.06.2002, S. 182–184 (Elke Schmitter).',
 'Der Tagesspiegel, 31.05.2002, S. 29 (Hellmuth Karasek).',
 'Süddeutsche Zeitung (München), 31.05.2002 (Lothar Müller).',
 'Frankfurter Allgemeine Zeitung, 29.05.2002 (Frank Schirrmacher).',
 'Literaturkritik.de, 01.06.2002 (www.literaturkritik.de/public/rezension.php?rez_id=5079, zuletzt abgerufen: 15.01.15) (Kai Köhler).',
 'Perlentaucher.de, 05.06.2002 (http://www.perlentaucher.de/vom-nachttisch-geraeumt/martin-walsers-tod-eines-kritikers.html, zuletzt abgerufen: 16.02.2015) (Arno Widmann).',
 'Frankfurter Rundschau, 31.05.2002, S. 17 (Marius Meller).',
 'Kurier (Österreich), 22.06.2002, S.30 (o. V.).',
 'Sonntagszeitung, 02.06.2002, S. 51 (Matthias Lerf).',
 'Lausitzer Rundschau, 03.06.2002 (Ulrike Koltermann).',
 'Main-Taunus-Kurier, 03.07.2002 (Viola Bolduan).',
 'Südkurier, 05.06.2002 (S. Dettlinger).',
 'Die Presse, 01.06.2002 (Wolfgang Freitag).',
 'Frankfurter Neue Presse, 27.06.2002, S. 3 (Michael Kluger).',
 'die tageszeitung, 01.06.2002 (Dirk Knipphals).',
 'Handelsblatt, 14.06.2002 (Jörg Magenau).',
 'Bonner General-Anzeiger, 05.06.2002, S. 12 (Peter Mohr).',
 'Hamburger Morgenpost, 21.06.2002 (Ira Panic).',
 'Saarbrücker Zeitung, 26.06.2002 (Christoph Schreiner).',
 'Hamburger Abendblatt, 25.06.2002, S. 8 (Armgard Seegers).',
 'Berliner Zeitung, 28.06.2002, S. 9 (Stephan Speicher).',
 'Nordkurier, 04.06.2002 (Detlef Stapf).',
 'Kölnische Rundschau, 28.06.2002 (Hartmut Wilmes).',
 'Wormser, Zeitung, 04.06.2002 (Jens Frederiksen).',
 'Thüringer Allgemeine, 05.06.2002 (Henryk Goldberg).',
 'Rhein-Zeitung, 06.06.2002 (Andreas Pecht).',
 'Rheinische Post, 01.06.2002 (Lothar Schröder).',
 'Rheinische Post, 25.06.2002 (Rafael Seligmann).',
 'Die Rheinpfalz, 04.06.2002 (Markus Clauer).',
 'Mitteldeutsche Zeitung, 31.05.2002 (Christian Eger).',
 'Berliner Zeitung, 01.06.2002, S. 11 (Harald Jähner).',
 'Kölner Stadt-Anzeiger, 27.06.2002 (Martin Oehlen).',
 'Die Welt, 31.05.2002 (Ulrich Weinzierl).',
 'Badische Zeitung, 03.06.2002 (Bettina Schulte).',
 'Mannheimer Morgen, 27.06.2002, S. 8 (Thomas Groß).',
 'Jüdische Allgemeine, 06.06.2002 (Michael Wuliger).',
 'Die Welt (Die literarische Welt), 01.03.2003, S. 4. (Uwe Wittstock).',
 'Frankfurter Allgemeine Zeitung, 01.03.2003, S. 44 (Richard Kämmerlings).',
 'die tageszeitung, 07.03.2003, S. 17 (Manuel Gogos).',
 'Süddeutsche Zeitung, 13.03.2003, S. 16 (Christoph Bartmann).',
 'Der Spiegel, 01.03.2003, S. 146 (Doja Hacker).',
 'Frankfurter Rundschau, 08.03.2003, S. 12 (Peter Michalzik).',
 'Die Weltwoche, 20.03.2003, S. 84 (Hans-Peter Kunisch).',
 'Süddeutsche Zeitung, 12.04.2003, S. 18 (Marica Bodrozic).',
 'Der Standard (Album), 19.04.2003, S. A7 (Günther Fischer).',
 'Rheinischer Merkur, 17.07.03 (Anastasia Simopoulos).',
 'Der Tagesspiegel, 23.07.2003, S. 23 (Peter von Becker).',
 'Neue Zürcher Zeitung, 19.03.2003 (Dorothea Dieckmann).',
 'Stuttgarter Zeitung, 12.03.2003 (o. V.).',
 'Saarbrücker Zeitung, 11.04.2003 (Bert Bugdahl).',
 'Die Zeit, 13.03.2003 (Jens Jessen).',
 'Säschische Zeitung, 15.03.2003 (Karin Großmann).',
 'Nürnberger Nachrichten, 12.03.2003 (Roland Mischke).',
 'Bonner General-Anzeiger, 11.04.2003, S. 14 (Peter Mohr).',
 'Dlf, 23.03.2003 (Shirin Sojitrawalla) (www.deutschlandfunk.de/esra.700.de.html?dram:article_id=80790)',
 'Welt am Sonntag, 16.03.2003, S. 5 (gt).',
 'die tageszeitung, 05.07.2003 (Lottmann, Joachim)',
 'die tageszeitung, 09.08.2003, S. 13 (Gerrit Bartels).',
 'Die Presse (Spectrum), 09.08.2003, S. VI (Christoph Bartmann).',
 'Stuttgarter Zeitung, 01.08.2003, S. 32 (Helmut Böttiger).',
 'Neue Zürcher Zeitung, 29.07.2003, S. 33 (Andreas Breitenstein).',
 'Der Tagesspiegel, 01.08.2003, S. 25 (Caroline Fetscher).',
 'Falter, 01.08.2003, S. 56–57 (Bernhard Fetz).',
 'Der Standard (Album), 26.07.2003, S. A5 (Stefan Gmünder).',
 'Frankfurter Allgemeine Zeitung, 02.08.2003, S. 42 (Richard Kämmerlings).',
 'Die Welt (Die literarische Welt), 02.08.2003, S. 3 (Tilman Krause).',
 'Frankfurter Rundschau, 08.10.2003, S. 11 (Heribert Kuhn).',
 'Tiroler Tageszeitung (Magazin), 26.07.2003, S. 6 (Christine Mach).',
 'ff - Das Südtiroler Wochenmagazin, 31.07.2003, S. 44–45 (Georg Mair).',
 'Der Freitag, 07.01.2005, S. 14 (Norbert Mappes-Niediek).',
 'Rheinischer Merkur, 07.08.2003, S. 20 (Roland Mischke).',
 'Süddeutsche Zeitung, 26.07.2003, S. 11 (Lothar Müller).',
 'Neues Deutschland, 08.12.2003, S. 12 (Sabine Neubert).',
 'Oberöstereichische Nachrichten, 18.09.2003, S. 8 (Christian Pichler).',
 'Echo, 25.09.2003, S. 112 (ra).',
 'Die Zeit, 22.12.2003, S. 46 (Iris Radisch).',
 'Sächsische Zeitung, 06.08.2003, S. 7 (Cornelia Resik).',
 'Die Weltwoche, 21.08.2003, S. 76–77 (Hansjörg Schertenleib).',
 'Wiener Zeitung (extra), 10.10.2003, S. 6 (Uwe Schütte).',
 'Die Furche, 14.08.2003, S. 18 (Brigitte Schwens-Harrant).',
 'profil, 04.08.2003, S. 125 (Daniela Strigl).',
 'Der Spiegel, 28.07.2003, S. 124 (Barbara Supp).',
 'Salzburger Nachrichten (Lebensart), 25.11.2003, S. VII (Anton Thuswaldner).',
 'Basler Zeitung, 29.08.2003 (o. V.).',
 'Kurier, 02.08.2003 (o. V.).',
 'Passauer Neue Presse, 15.11.2003 (Gudrun Bergmann).',
 'Darmstädter Echo, 27.08.2003 (Breckner).',
 'Nürnberger Zeitung 20.08.2003 (Thomas Heinold).',
 'Neue Vorarlberger Tageszeitung, 07.08.2003 (Werner Krause).',
 'Kölner Stadtanzeiger, 13.08.2003 (Friedhelm Marx).',
 'Aargauer Zeitung, 03.09.2003, S. 11 (Hans Ulrich Probst).',
 'Format, 25.07.2003 (Susanne Rössler).',
 'Rheinische Post, 29.10.2003 (Lothar Schröder).',
 'die tageszeitung, 04.09.2003 (Carola Ebeling).']

In [3]:
#Datum extrahieren

matches = {}
p = re.compile('(?P<day>\d{1,2}.)\s??(?P<month>\d{1,2}.|[a-z,A-Z,ä,ü,ö]{1,13})\s??(?P<year>\d{4})')
i=0

for line in lines:
    
    #print(line)
    m = p.search(line)
    if m:
        i += 1
        Tag, Monat, Jahr = m.group(1), m.group(2), m.group(3)
        
        #print("Tag", m.group(1), "Monat", m.group(2), "Jahr", m.group(3))
        #age = int(m.group(3)) - int(m.group(2))
        #matches[m.group(1)] = [m.group(2), m.group(3), age]
        matches[i] = line, Tag, Monat, Jahr
    else:
        pass
        #matches[i] = line
    
for key in matches.keys():
    line, Tag, Monat, Jahr = matches[key]
    print(key, line[:200])

1 ﻿Die Zeit, 02.06.2002 (Jan Assheuer).
2 Süddeutsche Zeitung (München), 05.06. 2002 (Joachim Kaiser).
3 Der Standard (Album), 06.07.2002, S. 1 (Daniela Strigl).
4 Die Furche, 18.07.2002, S. 15 (Kurt Wimmer).
5 Frankfurter Rundschau, 27.06.2002, S. 22 (Jochen Hörisch).
6 Frankfurter Rundschau, 27.06.2002, S. 19 (Ruth Klüger).
7 Der Tagesspiegel, 27.06.2002, S. 27 (Peter von Becker).
8 Die Zeit, 27.06.2002, S. 45 (Jens Jessen).
9 Frankfurter Allgemeine Zeitung, 27.06.2002, S. 47–48 (Jan Philipp Reemtsma).
10 Oberösterreichische Nachrichten, 05.07.2002, S. 7 (Christian Pichler).
11 Die Presse (Spectrum), 29.06.2002, S. V (Christoph Bartmann).
12 Neues Deutschland, 26.06.2002, S. 9 (Hans-Dieter Schütt).
13 Die Welt, 27.06.2002, S. 28 (Tilman Krause).
14 Der Freitag, 14.06.2002, S. 14 (Ingo Arend).
15 Die Zeit, 06.06.2002, S. 39 (Ulrich Greiner).
16 die tageszeitung, 17.06.2002, S. 20 (Klaus Bittermann).
17 Neue Zürcher Zeitung, 01.06.2002, S. 33 (Martin Meyer).
18 Tiroler Tageszeitung (Magazin), 08.06.2002, S. 6 (Sabine Strobl).
19 Der Freitag, 07.06.2002, S. 11 (Ulrich Müller-Schöll).
20 Rheinischer Merkur, 06.06.2002, S. 8 (Ulrich Baron).
21 Rheinischer Merkur, 06.06.2002, S. 8 (Andreas Öhler).
22 Vorarlberger Nachrichten, 15.06.2002, S. D11 (o. V.)
23 Der Standard, 03.06.2002, S. 22 (Richard Reichensperger).
24 profil, 03.06.2002, S. 132 (Willi Winkler).
25 Der Spiegel, 03.06.2002, S. 182–184 (Elke Schmitter).
26 Der Tagesspiegel, 31.05.2002, S. 29 (Hellmuth Karasek).
27 Süddeutsche Zeitung (München), 31.05.2002 (Lothar Müller).
28 Frankfurter Allgemeine Zeitung, 29.05.2002 (Frank Schirrmacher).
29 Literaturkritik.de, 01.06.2002 (www.literaturkritik.de/public/rezension.php?rez_id=5079, zuletzt abgerufen: 15.01.15) (Kai Köhler).
30 Perlentaucher.de, 05.06.2002 (http://www.perlentaucher.de/vom-nachttisch-geraeumt/martin-walsers-tod-eines-kritikers.html, zuletzt abgerufen: 16.02.2015) (Arno Widmann).
31 Frankfurter Rundschau, 31.05.2002, S. 17 (Marius Meller).
32 Kurier (Österreich), 22.06.2002, S.30 (o. V.).
33 Sonntagszeitung, 02.06.2002, S. 51 (Matthias Lerf).
34 Lausitzer Rundschau, 03.06.2002 (Ulrike Koltermann).
35 Main-Taunus-Kurier, 03.07.2002 (Viola Bolduan).
36 Südkurier, 05.06.2002 (S. Dettlinger).
37 Die Presse, 01.06.2002 (Wolfgang Freitag).
38 Frankfurter Neue Presse, 27.06.2002, S. 3 (Michael Kluger).
39 die tageszeitung, 01.06.2002 (Dirk Knipphals).
40 Handelsblatt, 14.06.2002 (Jörg Magenau).
41 Bonner General-Anzeiger, 05.06.2002, S. 12 (Peter Mohr).
42 Hamburger Morgenpost, 21.06.2002 (Ira Panic).
43 Saarbrücker Zeitung, 26.06.2002 (Christoph Schreiner).
44 Hamburger Abendblatt, 25.06.2002, S. 8 (Armgard Seegers).
45 Berliner Zeitung, 28.06.2002, S. 9 (Stephan Speicher).
46 Nordkurier, 04.06.2002 (Detlef Stapf).
47 Kölnische Rundschau, 28.06.2002 (Hartmut Wilmes).
48 Wormser, Zeitung, 04.06.2002 (Jens Frederiksen).
49 Thüringer Allgemeine, 05.06.2002 (Henryk Goldberg).
50 Rhein-Zeitung, 06.06.2002 (Andreas Pecht).
51 Rheinische Post, 01.06.2002 (Lothar Schröder).
52 Rheinische Post, 25.06.2002 (Rafael Seligmann).
53 Die Rheinpfalz, 04.06.2002 (Markus Clauer).
54 Mitteldeutsche Zeitung, 31.05.2002 (Christian Eger).
55 Berliner Zeitung, 01.06.2002, S. 11 (Harald Jähner).
56 Kölner Stadt-Anzeiger, 27.06.2002 (Martin Oehlen).
57 Die Welt, 31.05.2002 (Ulrich Weinzierl).
58 Badische Zeitung, 03.06.2002 (Bettina Schulte).
59 Mannheimer Morgen, 27.06.2002, S. 8 (Thomas Groß).
60 Jüdische Allgemeine, 06.06.2002 (Michael Wuliger).
61 Die Welt (Die literarische Welt), 01.03.2003, S. 4. (Uwe Wittstock).
62 Frankfurter Allgemeine Zeitung, 01.03.2003, S. 44 (Richard Kämmerlings).
63 die tageszeitung, 07.03.2003, S. 17 (Manuel Gogos).
64 Süddeutsche Zeitung, 13.03.2003, S. 16 (Christoph Bartmann).
65 Der Spiegel, 01.03.2003, S. 146 (Doja Hacker).
66 Frankfurter Rundschau, 08.03.2003, S. 12 (Peter Michalzik).
67 Die Weltwoche, 20.03.2003, S. 84 (Hans-Peter Kunisch).
68 Süddeutsche Zeitung, 12.04.2003, S. 18 (Marica Bodrozic).
69 Der Standard (Album), 19.04.2003, S. A7 (Günther Fischer).
70 Der Tagesspiegel, 23.07.2003, S. 23 (Peter von Becker).
71 Neue Zürcher Zeitung, 19.03.2003 (Dorothea Dieckmann).
72 Stuttgarter Zeitung, 12.03.2003 (o. V.).
73 Saarbrücker Zeitung, 11.04.2003 (Bert Bugdahl).
74 Die Zeit, 13.03.2003 (Jens Jessen).
75 Säschische Zeitung, 15.03.2003 (Karin Großmann).
76 Nürnberger Nachrichten, 12.03.2003 (Roland Mischke).
77 Bonner General-Anzeiger, 11.04.2003, S. 14 (Peter Mohr).
78 Dlf, 23.03.2003 (Shirin Sojitrawalla) (www.deutschlandfunk.de/esra.700.de.html?dram:article_id=80790)
79 Welt am Sonntag, 16.03.2003, S. 5 (gt).
80 die tageszeitung, 05.07.2003 (Lottmann, Joachim)
81 die tageszeitung, 09.08.2003, S. 13 (Gerrit Bartels).
82 Die Presse (Spectrum), 09.08.2003, S. VI (Christoph Bartmann).
83 Stuttgarter Zeitung, 01.08.2003, S. 32 (Helmut Böttiger).
84 Neue Zürcher Zeitung, 29.07.2003, S. 33 (Andreas Breitenstein).
85 Der Tagesspiegel, 01.08.2003, S. 25 (Caroline Fetscher).
86 Falter, 01.08.2003, S. 56–57 (Bernhard Fetz).
87 Der Standard (Album), 26.07.2003, S. A5 (Stefan Gmünder).
88 Frankfurter Allgemeine Zeitung, 02.08.2003, S. 42 (Richard Kämmerlings).
89 Die Welt (Die literarische Welt), 02.08.2003, S. 3 (Tilman Krause).
90 Frankfurter Rundschau, 08.10.2003, S. 11 (Heribert Kuhn).
91 Tiroler Tageszeitung (Magazin), 26.07.2003, S. 6 (Christine Mach).
92 ff - Das Südtiroler Wochenmagazin, 31.07.2003, S. 44–45 (Georg Mair).
93 Der Freitag, 07.01.2005, S. 14 (Norbert Mappes-Niediek).
94 Rheinischer Merkur, 07.08.2003, S. 20 (Roland Mischke).
95 Süddeutsche Zeitung, 26.07.2003, S. 11 (Lothar Müller).
96 Neues Deutschland, 08.12.2003, S. 12 (Sabine Neubert).
97 Oberöstereichische Nachrichten, 18.09.2003, S. 8 (Christian Pichler).
98 Echo, 25.09.2003, S. 112 (ra).
99 Die Zeit, 22.12.2003, S. 46 (Iris Radisch).
100 Sächsische Zeitung, 06.08.2003, S. 7 (Cornelia Resik).
101 Die Weltwoche, 21.08.2003, S. 76–77 (Hansjörg Schertenleib).
102 Wiener Zeitung (extra), 10.10.2003, S. 6 (Uwe Schütte).
103 Die Furche, 14.08.2003, S. 18 (Brigitte Schwens-Harrant).
104 profil, 04.08.2003, S. 125 (Daniela Strigl).
105 Der Spiegel, 28.07.2003, S. 124 (Barbara Supp).
106 Salzburger Nachrichten (Lebensart), 25.11.2003, S. VII (Anton Thuswaldner).
107 Basler Zeitung, 29.08.2003 (o. V.).
108 Kurier, 02.08.2003 (o. V.).
109 Passauer Neue Presse, 15.11.2003 (Gudrun Bergmann).
110 Darmstädter Echo, 27.08.2003 (Breckner).
111 Nürnberger Zeitung 20.08.2003 (Thomas Heinold).
112 Neue Vorarlberger Tageszeitung, 07.08.2003 (Werner Krause).
113 Kölner Stadtanzeiger, 13.08.2003 (Friedhelm Marx).
114 Aargauer Zeitung, 03.09.2003, S. 11 (Hans Ulrich Probst).
115 Format, 25.07.2003 (Susanne Rössler).
116 Rheinische Post, 29.10.2003 (Lothar Schröder).
117 die tageszeitung, 04.09.2003 (Carola Ebeling).

In [4]:
#erste Rez suchen
import datetime
from datetime import date
import unicodedata as ud


dateswalser = []
datesbiller = []
datesgstrein = []
Monate = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"]
j = 0
for rez in matches.keys():
    j +=1
    
        
    try:
        line, Tag, Monat, Jahr = matches[rez]
        Tag = Tag.strip(".")
        Monat = Monat.strip(".")
        Monat = ud.normalize('NFC',Monat)
        i=0
        for mon in Monate:
            i += 1
            if mon.startswith(Monat):
                Monat = str(i)
                #print(Monat)
        
        Jahr = Jahr.strip(".")
        if j <= 61:
            dateswalser.append('-'.join([Tag, Monat, Jahr]))
        elif j<=82:
            datesbiller.append('-'.join([Tag, Monat, Jahr]))
        else:
            datesgstrein.append('-'.join([Tag, Monat, Jahr]))
    except:
        pass
    

walsermin= sorted(dateswalser, key=lambda x: datetime.datetime.strptime(x, '%d-%m-%Y'))[0]
print(walsermin)
billermin= sorted(datesbiller, key=lambda x: datetime.datetime.strptime(x, '%d-%m-%Y'))[0]
print(billermin)
gstreinmin= sorted(datesgstrein, key=lambda x: datetime.datetime.strptime(x, '%d-%m-%Y'))[0]
print(gstreinmin)

29-05-2002
01-03-2003
25-07-2003

In [5]:
# Tage seit Erstrezension berechenen
matches = {}
j = 0
for line in lines:
    j +=1
    i=0
    #print(line)
    m = p.search(line)
    if m:
        Tag, Monat, Jahr = m.group(1).strip("."), m.group(2).strip("."), m.group(3).strip(".")
        i=0
        for mon in Monate:
            i += 1
            if mon.startswith(Monat):
                Monat = str(i)
        #print(Monat)
        
                
        a = date(int(Jahr),int(Monat),int(Tag))
        print("a", a)
        if j<=61:
            min = walsermin.split("-")
            Tag2 = int(min[0])
            Monat2 = int(min[1])
            Jahr2 = int(min[2])
            b= date(Jahr2, Monat2, Tag2)
        elif j <= 82:
            min = billermin.split("-")
            Tag2 = int(min[0])
            Monat2 = int(min[1])
            Jahr2 = int(min[2])
            b= date(Jahr2, Monat2, Tag2)
        else:
            min = gstreinmin.split("-")
            Tag2 = int(min[0])
            Monat2 = int(min[1])
            Jahr2 = int(min[2])
            b= date(Jahr2, Monat2, Tag2)
        print("min", b)
        Tage = (a-b).days
        print("diff:", Tage)
        #print("Tag", m.group(1), "Monat", m.group(2), "Jahr", m.group(3))
        #age = int(m.group(3)) - int(m.group(2))
        #matches[m.group(1)] = [m.group(2), m.group(3), age]
        matches[line] = Tag, Monat, Jahr, Tage
    else:
        matches[line] = ""

a 2002-06-02
min 2002-05-29
diff: 4
a 2002-06-05
min 2002-05-29
diff: 7
a 2002-07-06
min 2002-05-29
diff: 38
a 2002-07-18
min 2002-05-29
diff: 50
a 2002-06-27
min 2002-05-29
diff: 29
a 2002-06-27
min 2002-05-29
diff: 29
a 2002-06-27
min 2002-05-29
diff: 29
a 2002-06-27
min 2002-05-29
diff: 29
a 2002-06-27
min 2002-05-29
diff: 29
a 2002-07-05
min 2002-05-29
diff: 37
a 2002-06-29
min 2002-05-29
diff: 31
a 2002-06-26
min 2002-05-29
diff: 28
a 2002-06-27
min 2002-05-29
diff: 29
a 2002-06-14
min 2002-05-29
diff: 16
a 2002-06-06
min 2002-05-29
diff: 8
a 2002-06-17
min 2002-05-29
diff: 19
a 2002-06-01
min 2002-05-29
diff: 3
a 2002-06-08
min 2002-05-29
diff: 10
a 2002-06-07
min 2002-05-29
diff: 9
a 2002-06-06
min 2002-05-29
diff: 8
a 2002-06-06
min 2002-05-29
diff: 8
a 2002-06-15
min 2002-05-29
diff: 17
a 2002-06-03
min 2002-05-29
diff: 5
a 2002-06-03
min 2002-05-29
diff: 5
a 2002-06-03
min 2002-05-29
diff: 5
a 2002-05-31
min 2002-05-29
diff: 2
a 2002-05-31
min 2002-05-29
diff: 2
a 2002-05-29
min 2002-05-29
diff: 0
a 2002-06-01
min 2002-05-29
diff: 3
a 2002-06-05
min 2002-05-29
diff: 7
a 2002-05-31
min 2002-05-29
diff: 2
a 2002-06-22
min 2002-05-29
diff: 24
a 2002-06-02
min 2002-05-29
diff: 4
a 2002-06-03
min 2002-05-29
diff: 5
a 2002-07-03
min 2002-05-29
diff: 35
a 2002-06-05
min 2002-05-29
diff: 7
a 2002-06-01
min 2002-05-29
diff: 3
a 2002-06-27
min 2002-05-29
diff: 29
a 2002-06-01
min 2002-05-29
diff: 3
a 2002-06-14
min 2002-05-29
diff: 16
a 2002-06-05
min 2002-05-29
diff: 7
a 2002-06-21
min 2002-05-29
diff: 23
a 2002-06-26
min 2002-05-29
diff: 28
a 2002-06-25
min 2002-05-29
diff: 27
a 2002-06-28
min 2002-05-29
diff: 30
a 2002-06-04
min 2002-05-29
diff: 6
a 2002-06-28
min 2002-05-29
diff: 30
a 2002-06-04
min 2002-05-29
diff: 6
a 2002-06-05
min 2002-05-29
diff: 7
a 2002-06-06
min 2002-05-29
diff: 8
a 2002-06-01
min 2002-05-29
diff: 3
a 2002-06-25
min 2002-05-29
diff: 27
a 2002-06-04
min 2002-05-29
diff: 6
a 2002-05-31
min 2002-05-29
diff: 2
a 2002-06-01
min 2002-05-29
diff: 3
a 2002-06-27
min 2002-05-29
diff: 29
a 2002-05-31
min 2002-05-29
diff: 2
a 2002-06-03
min 2002-05-29
diff: 5
a 2002-06-27
min 2002-05-29
diff: 29
a 2002-06-06
min 2002-05-29
diff: 8
a 2003-03-01
min 2002-05-29
diff: 276
a 2003-03-01
min 2003-03-01
diff: 0
a 2003-03-07
min 2003-03-01
diff: 6
a 2003-03-13
min 2003-03-01
diff: 12
a 2003-03-01
min 2003-03-01
diff: 0
a 2003-03-08
min 2003-03-01
diff: 7
a 2003-03-20
min 2003-03-01
diff: 19
a 2003-04-12
min 2003-03-01
diff: 42
a 2003-04-19
min 2003-03-01
diff: 49
a 2003-07-23
min 2003-03-01
diff: 144
a 2003-03-19
min 2003-03-01
diff: 18
a 2003-03-12
min 2003-03-01
diff: 11
a 2003-04-11
min 2003-03-01
diff: 41
a 2003-03-13
min 2003-03-01
diff: 12
a 2003-03-15
min 2003-03-01
diff: 14
a 2003-03-12
min 2003-03-01
diff: 11
a 2003-04-11
min 2003-03-01
diff: 41
a 2003-03-23
min 2003-03-01
diff: 22
a 2003-03-16
min 2003-03-01
diff: 15
a 2003-07-05
min 2003-03-01
diff: 126
a 2003-08-09
min 2003-03-01
diff: 161
a 2003-08-09
min 2003-07-25
diff: 15
a 2003-08-01
min 2003-07-25
diff: 7
a 2003-07-29
min 2003-07-25
diff: 4
a 2003-08-01
min 2003-07-25
diff: 7
a 2003-08-01
min 2003-07-25
diff: 7
a 2003-07-26
min 2003-07-25
diff: 1
a 2003-08-02
min 2003-07-25
diff: 8
a 2003-08-02
min 2003-07-25
diff: 8
a 2003-10-08
min 2003-07-25
diff: 75
a 2003-07-26
min 2003-07-25
diff: 1
a 2003-07-31
min 2003-07-25
diff: 6
a 2005-01-07
min 2003-07-25
diff: 532
a 2003-08-07
min 2003-07-25
diff: 13
a 2003-07-26
min 2003-07-25
diff: 1
a 2003-12-08
min 2003-07-25
diff: 136
a 2003-09-18
min 2003-07-25
diff: 55
a 2003-09-25
min 2003-07-25
diff: 62
a 2003-12-22
min 2003-07-25
diff: 150
a 2003-08-06
min 2003-07-25
diff: 12
a 2003-08-21
min 2003-07-25
diff: 27
a 2003-10-10
min 2003-07-25
diff: 77
a 2003-08-14
min 2003-07-25
diff: 20
a 2003-08-04
min 2003-07-25
diff: 10
a 2003-07-28
min 2003-07-25
diff: 3
a 2003-11-25
min 2003-07-25
diff: 123
a 2003-08-29
min 2003-07-25
diff: 35
a 2003-08-02
min 2003-07-25
diff: 8
a 2003-11-15
min 2003-07-25
diff: 113
a 2003-08-27
min 2003-07-25
diff: 33
a 2003-08-20
min 2003-07-25
diff: 26
a 2003-08-07
min 2003-07-25
diff: 13
a 2003-08-13
min 2003-07-25
diff: 19
a 2003-09-03
min 2003-07-25
diff: 40
a 2003-07-25
min 2003-07-25
diff: 0
a 2003-10-29
min 2003-07-25
diff: 96
a 2003-09-04
min 2003-07-25
diff: 41

In [6]:
#Daten schreiben
os.chdir("C:\\Users\\Benjamin\\Dropbox\\Wissenschaft\\Fiktion und Genre\\Habil\\Python")
with open("Tage_seit_Erstrezension.csv", "w", encoding="utf8") as file:
    for rez in matches.keys():
        file.write(str(rez)+";")
        
        for element in matches[rez]:
            file.write(str(element)+";")
        file.write("\n")